# Created by Crt Vavros, copyright © 2022 ZeroPass. All rights reserved.
name: cccd_vietnam
description: Read and write data from ID card Viet Nam using NFC
homepage: https://github.com/phanvankhaicd/cccd_vietnam
version: 1.0.0

environment:
  sdk: '>=2.17.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  archive: ^3.1.2
  collection: ^1.16.0
  convert: ^3.0.0
  crypto: ^3.0.1
  expandable: ^5.0.1
  fixnum: ^1.0.0
  flutter_nfc_kit: ^3.4.2
  logging: ^1.0.2
  meta: ^1.3.0
  tripledes_nullsafety: ^1.0.3
  pointycastle: ^3.7.4
  diffie_hellman: ^0.1.2
  crypto_keys_plus: ^0.4.0 # till crypto_keys lib is not updated
  flutter_platform_widgets: ^3.3.5
  intl: ^0.19.0
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  lints: ^2.0.0
  test: ^1.16.5

flutter:
  uses-material-design: true
